# Generated by Django 2.0.2 on 2018-12-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
    ]
